"""mains-first

Revision ID: 294ebb89c6be
Revises: 5398974258a7
Create Date: 2025-07-08 16:48:27.957828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294ebb89c6be'
down_revision: Union[str, Sequence[str], None] = '5398974258a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_results', 'token_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('analysis_results_script_id_fkey'), 'analysis_results', type_='foreignkey')
    op.drop_column('analysis_results', 'script_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('script_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('analysis_results_script_id_fkey'), 'analysis_results', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.alter_column('analysis_results', 'token_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
