"""Add script_id to AnalysisResult for script-level analysis

Revision ID: 5398974258a7
Revises: 7c7dcc563b6b
Create Date: 2025-07-08 11:45:46.198912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5398974258a7'
down_revision: Union[str, Sequence[str], None] = '7c7dcc563b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('script_id', sa.Integer(), nullable=True))
    op.alter_column('analysis_results', 'token_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'analysis_results', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_results', type_='foreignkey')
    op.alter_column('analysis_results', 'token_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('analysis_results', 'script_id')
    # ### end Alembic commands ###
