"""Add thumbnail_url to tokens table

Revision ID: 844f39fddc02
Revises: 14f6cbc8e929
Create Date: 2025-07-12 18:03:07.396911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844f39fddc02'
down_revision: Union[str, Sequence[str], None] = '14f6cbc8e929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'thumbnail_url')
    # ### end Alembic commands ###
