"""baseline before url

Revision ID: 8f5d6297aa14
Revises: 
Create Date: 2025-07-03 00:31:46.550355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f5d6297aa14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('youtube_url', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('youtube_url')
    )
    op.create_index(op.f('ix_urls_actor_id'), 'urls', ['actor_id'], unique=False)
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.alter_column('tokens', 'youtube_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_tokens_youtube_url'), 'tokens', ['youtube_url'], unique=False)
    op.create_foreign_key(None, 'tokens', 'urls', ['youtube_url'], ['youtube_url'], ondelete='CASCADE')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'login_type')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'updated_at')
    op.create_foreign_key(None, 'words', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('login_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_index(op.f('ix_tokens_youtube_url'), table_name='tokens')
    op.alter_column('tokens', 'youtube_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_voice_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('results_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('results_pkey'))
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.drop_index(op.f('ix_urls_actor_id'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
