"""Remove username and hashed_password from User model

Revision ID: 99ed4b628e7d
Revises: 3a94977e87b6
Create Date: 2025-07-03 19:20:46.901133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99ed4b628e7d'
down_revision: Union[str, Sequence[str], None] = '3a94977e87b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alias_name'), table_name='actor_aliases')
    op.drop_index(op.f('ix_alias_name_trgm'), table_name='actor_aliases', postgresql_using='gin')
    op.drop_table('actor_aliases')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.create_index(op.f('ix_token_actors_id'), 'token_actors', ['id'], unique=False)
    op.alter_column('tokens', 'youtube_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_tokens_youtube_url'), 'tokens', ['youtube_url'], unique=False)
    op.alter_column('urls', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'hashed_password')
    op.create_foreign_key(None, 'words', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('urls', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_tokens_youtube_url'), table_name='tokens')
    op.alter_column('tokens', 'youtube_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_token_actors_id'), table_name='token_actors')
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_voice_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('results_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('results_pkey'))
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_table('actor_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('actor_aliases_actor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('actor_aliases_pkey')),
    sa.UniqueConstraint('actor_id', 'name', name=op.f('uq_actor_alias'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_alias_name_trgm'), 'actor_aliases', ['name'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_alias_name'), 'actor_aliases', ['name'], unique=False)
    # ### end Alembic commands ###
