"""add view_count column to tokens table

Revision ID: dcc86397bd53
Revises: e32a2da4a5be
Create Date: 2025-07-07 14:53:02.481677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc86397bd53'
down_revision: Union[str, Sequence[str], None] = 'e32a2da4a5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 먼저 nullable=True로 컬럼 추가
    op.add_column('tokens', sa.Column('view_count', sa.Integer(), nullable=True))
    
    # 2. 기존 데이터에 기본값 0 설정
    op.execute("UPDATE tokens SET view_count = 0 WHERE view_count IS NULL")
    
    # 3. NOT NULL 제약조건 추가
    op.alter_column('tokens', 'view_count', nullable=False, server_default='0')
    
    # 4. 인덱스 생성
    op.create_index(op.f('ix_tokens_view_count'), 'tokens', ['view_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_view_count'), table_name='tokens')
    op.drop_column('tokens', 'view_count')
    # ### end Alembic commands ###
